package cn.neyzoter.module.tf.serving;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tfserving.proto

public final class Tfserving {
  private Tfserving() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InstanceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Instance)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated double instance = 1;</code>
     * @return A list containing the instance.
     */
    java.util.List<Double> getInstanceList();
    /**
     * <code>repeated double instance = 1;</code>
     * @return The count of instance.
     */
    int getInstanceCount();
    /**
     * <code>repeated double instance = 1;</code>
     * @param index The index of the element to return.
     * @return The instance at the given index.
     */
    double getInstance(int index);
  }
  /**
   * Protobuf type {@code Instance}
   */
  public static final class Instance extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Instance)
      InstanceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Instance.newBuilder() to construct.
    private Instance(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Instance() {
      instance_ = emptyDoubleList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Instance();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Instance(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                instance_ = newDoubleList();
                mutable_bitField0_ |= 0x00000001;
              }
              instance_.addDouble(input.readDouble());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                instance_ = newDoubleList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                instance_.addDouble(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          instance_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Tfserving.internal_static_Instance_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Tfserving.internal_static_Instance_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Tfserving.Instance.class, Tfserving.Instance.Builder.class);
    }

    public static final int INSTANCE_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.DoubleList instance_;
    /**
     * <code>repeated double instance = 1;</code>
     * @return A list containing the instance.
     */
    @Override
    public java.util.List<Double>
        getInstanceList() {
      return instance_;
    }
    /**
     * <code>repeated double instance = 1;</code>
     * @return The count of instance.
     */
    public int getInstanceCount() {
      return instance_.size();
    }
    /**
     * <code>repeated double instance = 1;</code>
     * @param index The index of the element to return.
     * @return The instance at the given index.
     */
    public double getInstance(int index) {
      return instance_.getDouble(index);
    }
    private int instanceMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getInstanceList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(instanceMemoizedSerializedSize);
      }
      for (int i = 0; i < instance_.size(); i++) {
        output.writeDoubleNoTag(instance_.getDouble(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 8 * getInstanceList().size();
        size += dataSize;
        if (!getInstanceList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        instanceMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Tfserving.Instance)) {
        return super.equals(obj);
      }
      Tfserving.Instance other = (Tfserving.Instance) obj;

      if (!getInstanceList()
          .equals(other.getInstanceList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getInstanceCount() > 0) {
        hash = (37 * hash) + INSTANCE_FIELD_NUMBER;
        hash = (53 * hash) + getInstanceList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Tfserving.Instance parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Tfserving.Instance parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Tfserving.Instance parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Tfserving.Instance parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Tfserving.Instance parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Tfserving.Instance parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Tfserving.Instance parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Tfserving.Instance parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Tfserving.Instance parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Tfserving.Instance parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Tfserving.Instance parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Tfserving.Instance parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Tfserving.Instance prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Instance}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Instance)
        Tfserving.InstanceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Tfserving.internal_static_Instance_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Tfserving.internal_static_Instance_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Tfserving.Instance.class, Tfserving.Instance.Builder.class);
      }

      // Construct using Tfserving.Instance.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        instance_ = emptyDoubleList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Tfserving.internal_static_Instance_descriptor;
      }

      @Override
      public Tfserving.Instance getDefaultInstanceForType() {
        return Tfserving.Instance.getDefaultInstance();
      }

      @Override
      public Tfserving.Instance build() {
        Tfserving.Instance result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Tfserving.Instance buildPartial() {
        Tfserving.Instance result = new Tfserving.Instance(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          instance_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.instance_ = instance_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Tfserving.Instance) {
          return mergeFrom((Tfserving.Instance)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Tfserving.Instance other) {
        if (other == Tfserving.Instance.getDefaultInstance()) return this;
        if (!other.instance_.isEmpty()) {
          if (instance_.isEmpty()) {
            instance_ = other.instance_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInstanceIsMutable();
            instance_.addAll(other.instance_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Tfserving.Instance parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Tfserving.Instance) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.DoubleList instance_ = emptyDoubleList();
      private void ensureInstanceIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          instance_ = mutableCopy(instance_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated double instance = 1;</code>
       * @return A list containing the instance.
       */
      public java.util.List<Double>
          getInstanceList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(instance_) : instance_;
      }
      /**
       * <code>repeated double instance = 1;</code>
       * @return The count of instance.
       */
      public int getInstanceCount() {
        return instance_.size();
      }
      /**
       * <code>repeated double instance = 1;</code>
       * @param index The index of the element to return.
       * @return The instance at the given index.
       */
      public double getInstance(int index) {
        return instance_.getDouble(index);
      }
      /**
       * <code>repeated double instance = 1;</code>
       * @param index The index to set the value at.
       * @param value The instance to set.
       * @return This builder for chaining.
       */
      public Builder setInstance(
          int index, double value) {
        ensureInstanceIsMutable();
        instance_.setDouble(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double instance = 1;</code>
       * @param value The instance to add.
       * @return This builder for chaining.
       */
      public Builder addInstance(double value) {
        ensureInstanceIsMutable();
        instance_.addDouble(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double instance = 1;</code>
       * @param values The instance to add.
       * @return This builder for chaining.
       */
      public Builder addAllInstance(
          Iterable<? extends Double> values) {
        ensureInstanceIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, instance_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double instance = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearInstance() {
        instance_ = emptyDoubleList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Instance)
    }

    // @@protoc_insertion_point(class_scope:Instance)
    private static final Tfserving.Instance DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Tfserving.Instance();
    }

    public static Tfserving.Instance getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Instance>
        PARSER = new com.google.protobuf.AbstractParser<Instance>() {
      @Override
      public Instance parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Instance(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Instance> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Instance> getParserForType() {
      return PARSER;
    }

    @Override
    public Tfserving.Instance getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Instance_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Instance_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017tfserving.proto\"\034\n\010Instance\022\020\n\010instanc" +
      "e\030\001 \003(\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Instance_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Instance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Instance_descriptor,
        new String[] { "Instance", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
